<?php

/**
 * @file
 * Contains brc_social_media_feeds_custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function brc_social_media_feeds_custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the brc_social_media_feeds_custom module.
    case 'help.page.brc_social_media_feeds_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Configuration page the <a href=":link">Social Feeds</a> module.', [':link' => '/social_feeds/configuration']) . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function brc_social_media_feeds_custom_theme() {
  return [
    'brc_social_media_feeds_custom' => [
      'render element' => 'children',
    ],
  ];
}
