<?php

/**
 * @file
 * Contains migrate_file_to_media_custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_file_to_media_custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_file_to_media_custom module.
    case 'help.page.migrate_file_to_media_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrate file fields to media fields custom.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function migrate_file_to_media_custom_theme() {
  return [
    'migrate_file_to_media_custom' => [
      'render element' => 'children',
    ],
  ];
}
